def get_gastos_mock() -> list[dict]:
    return [
        {
            "id": 1,
            "motivo": "Alimentação",
            "descricao": "Almoço com cliente",
            "valor": 187.50,
            "data": "2025-02-10T12:30:00",
            "empresa": "Restaurante Sabor & Arte",
            "cnpj": "12.345.678/0001-90",
            "razao_social": "Sabor & Arte Ltda",
            "ramo_atividade": "Alimentação",
            "categoria": "Refeição",
            "tipo_gasto": "Corporativo",
            "boolean_aprovado": True,
            "data_aprovacao": "2025-02-11T09:00:00",
            "boolean_extornado": False,
            "data_extorno": None,
            "arquivo_extracao": None,
            "funcionario_id": 1,
        },
        {
            "id": 2,
            "motivo": "Transporte",
            "descricao": "Uber para reunião",
            "valor": 64.90,
            "data": "2025-02-12T08:15:00",
            "empresa": "Uber",
            "cnpj": "17.895.646/0001-87",
            "razao_social": "Uber do Brasil Tecnologia Ltda",
            "ramo_atividade": "Transporte",
            "categoria": "Mobilidade",
            "tipo_gasto": "Corporativo",
            "boolean_aprovado": True,
            "data_aprovacao": "2025-02-13T10:00:00",
            "boolean_extornado": False,
            "data_extorno": None,
            "arquivo_extracao": None,
            "funcionario_id": 2,
        },
        {
            "id": 3,
            "motivo": "Hospedagem",
            "descricao": "Hotel para viagem de negócios",
            "valor": 520.00,
            "data": "2025-02-15T14:00:00",
            "empresa": "Hotel Business Inn",
            "cnpj": "98.765.432/0001-10",
            "razao_social": "Business Inn Hotelaria S.A.",
            "ramo_atividade": "Hotelaria",
            "categoria": "Acomodação",
            "tipo_gasto": "Viagem",
            "boolean_aprovado": False,
            "data_aprovacao": None,
            "boolean_extornado": False,
            "data_extorno": None,
            "arquivo_extracao": None,
            "funcionario_id": 1,
        },
        {
            "id": 4,
            "motivo": "Material de Escritório",
            "descricao": "Compra de papelaria e insumos",
            "valor": 212.30,
            "data": "2025-02-18T10:45:00",
            "empresa": "Kalunga",
            "cnpj": "61.064.929/0001-72",
            "razao_social": "Kalunga Comércio e Indústria Ltda",
            "ramo_atividade": "Papelaria",
            "categoria": "Suprimentos",
            "tipo_gasto": "Operacional",
            "boolean_aprovado": True,
            "data_aprovacao": "2025-02-19T08:30:00",
            "boolean_extornado": False,
            "data_extorno": None,
            "arquivo_extracao": None,
            "funcionario_id": 3,
        },
        {
            "id": 5,
            "motivo": "Transporte",
            "descricao": "Passagem aérea São Paulo - Rio",
            "valor": 98.75,
            "data": "2025-02-20T06:00:00",
            "empresa": "Gol Linhas Aéreas",
            "cnpj": "06.164.253/0001-87",
            "razao_social": "Gol Linhas Aéreas Inteligentes S.A.",
            "ramo_atividade": "Aviação",
            "categoria": "Passagem",
            "tipo_gasto": "Viagem",
            "boolean_aprovado": True,
            "data_aprovacao": "2025-02-21T09:00:00",
            "boolean_extornado": True,
            "data_extorno": "2025-02-22T11:00:00",
            "arquivo_extracao": None,
            "funcionario_id": 2,
        },
    ]
